session_timeout: 3600 #Second
db_max_table_limit: 5
llm_configs:
  llm_model_name: gpt-4o-mini
  llm_max_iteration: 10
end_points:
  start_session: /start_session
  upload_csv: /upload_csv
  query: /query
  end_session: /end_session
server:
  redis_ip: 'localhost'
  redis_port: 6379
  app_ip: 0.0.0.0
  app_port: 8000